Convert APP and ASA indexes to ints.
Previously, code like this:
  transaction.ApplicationNoOpTxn(bidder, params, "10382")

would silently continue, but after signing and submitting, would
report:
algosdk.error.AlgodHTTPError: msgpack decode error [pos 93]: cannot decode unsigned integer: unrecognized descriptor byte: a8/string|bytes

This is a pretty obscure error to get for using a string id instead of
an int. We could type check and give an error when creating the
transaction, but Python APIs are usually more forgiving.  This change
calls int() on the index argument, so it will try to convert strings
if needed.